#!/bin/bash
set -e

echo "=== SuiteCRM Container Startup ==="

# ---------------------------------------------------------------------------
# Wait for database to be available
# ---------------------------------------------------------------------------
wait_for_db() {
    echo "Waiting for database at ${SUITECRM_RUNTIME_MYSQL_HOST}:${SUITECRM_RUNTIME_MYSQL_PORT}..."
    
    max_attempts=${DOCKER_DB_WAIT_MAX_ATTEMPTS:-30}
    wait_interval=${DOCKER_DB_WAIT_INTERVAL:-5}
    attempt=1
    
    while [ $attempt -le $max_attempts ]; do
        if php -r "
            \$conn = @new mysqli(
                '${SUITECRM_RUNTIME_MYSQL_HOST}',
                '${SUITECRM_RUNTIME_MYSQL_USER}',
                '${SUITECRM_RUNTIME_MYSQL_PASSWORD}',
                '${SUITECRM_RUNTIME_MYSQL_NAME}',
                ${SUITECRM_RUNTIME_MYSQL_PORT}
            );
            if (\$conn->connect_error) {
                exit(1);
            }
            exit(0);
        " 2>/dev/null; then
            echo "Database connection successful!"
            return 0
        fi
        
        echo "Attempt $attempt/$max_attempts - Database not ready, waiting ${wait_interval}s..."
        sleep $wait_interval
        attempt=$((attempt + 1))
    done
    
    echo "WARNING: Could not connect to database after $max_attempts attempts"
    echo "Container will start anyway - SuiteCRM installer may be needed"
    return 0
}

# ---------------------------------------------------------------------------
# Generate SuiteCRM legacy .env file from environment variables
# ---------------------------------------------------------------------------
generate_legacy_env() {
    local env_file="/var/www/html/public/legacy/.env"
    
    echo "Generating SuiteCRM legacy .env from environment variables..."
    
    cat > "$env_file" << EOF
# Auto-generated by docker-entrypoint.sh
# Do not edit manually - changes will be lost on container restart

DATABASE_URL="mysql://${SUITECRM_RUNTIME_MYSQL_USER}:${SUITECRM_RUNTIME_MYSQL_PASSWORD}@${SUITECRM_RUNTIME_MYSQL_HOST}:${SUITECRM_RUNTIME_MYSQL_PORT}/${SUITECRM_RUNTIME_MYSQL_NAME}"
EOF
    
    chown www-data:www-data "$env_file"
    chmod 640 "$env_file"
}

# ---------------------------------------------------------------------------
# Generate or update config_override.php for cloud-native settings
# ---------------------------------------------------------------------------
generate_config_override() {
    local config_file="/var/www/html/public/legacy/config_override.php"
    
    echo "Generating config_override.php for cloud-native deployment..."
    
    cat > "$config_file" << 'PHPEOF'
<?php
// Auto-generated by docker-entrypoint.sh
// Cloud-native configuration for Azure Container Apps

// Database configuration from environment (values must be provided via docker-compose.yml)
$sugar_config['dbconfig']['db_host_name'] = getenv('SUITECRM_RUNTIME_MYSQL_HOST');
$sugar_config['dbconfig']['db_port'] = getenv('SUITECRM_RUNTIME_MYSQL_PORT');
$sugar_config['dbconfig']['db_user_name'] = getenv('SUITECRM_RUNTIME_MYSQL_USER');
$sugar_config['dbconfig']['db_password'] = getenv('SUITECRM_RUNTIME_MYSQL_PASSWORD') ?: '';
$sugar_config['dbconfig']['db_name'] = getenv('SUITECRM_RUNTIME_MYSQL_NAME');
$sugar_config['dbconfig']['db_type'] = 'mysql';
$sugar_config['dbconfig']['db_manager'] = 'MysqliManager';

// Azure MySQL requires SSL
$sugar_config['dbconfig']['db_ssl_enabled'] = filter_var(getenv('SUITECRM_RUNTIME_MYSQL_SSL_ENABLED'), FILTER_VALIDATE_BOOLEAN);
$sugar_config['dbconfig']['db_ssl_ca'] = getenv('SUITECRM_RUNTIME_MYSQL_SSL_CA');
$sugar_config['dbconfig']['db_ssl_verify'] = filter_var(getenv('SUITECRM_RUNTIME_MYSQL_SSL_VERIFY'), FILTER_VALIDATE_BOOLEAN);

// Site URL from environment
$sugar_config['site_url'] = getenv('SUITECRM_SITE_URL');

// Session handling - use database for stateless containers
$sugar_config['session_dir'] = '';
$sugar_config['session_gc'] = array(
    'enable' => true,
    'gc_probability' => 1,
    'gc_divisor' => 100,
);

// Cache configuration
$sugar_config['cache_dir'] = 'cache/';
$sugar_config['external_cache_disabled'] = false;

// Log configuration - output to stdout for container logging
$sugar_config['log_dir'] = '/dev';
$sugar_config['log_file'] = 'stdout';
$sugar_config['logger']['level'] = getenv('SUITECRM_LOG_LEVEL') ?: 'warning';

// Upload settings
$sugar_config['upload_dir'] = 'upload/';
// Convert DOCKER_PHP_UPLOAD_MAX_FILESIZE (e.g., "100M") to bytes, default 100MB
$upload_size = getenv('DOCKER_PHP_UPLOAD_MAX_FILESIZE') ?: '100M';
$upload_bytes = (int)$upload_size;
if (preg_match('/(\d+)([KMG])/i', $upload_size, $matches)) {
    $upload_bytes = (int)$matches[1];
    switch (strtoupper($matches[2])) {
        case 'K': $upload_bytes *= 1024; break;
        case 'M': $upload_bytes *= 1024 * 1024; break;
        case 'G': $upload_bytes *= 1024 * 1024 * 1024; break;
    }
}
$sugar_config['upload_maxsize'] = $upload_bytes;

// Disable installer after first run
$sugar_config['installer_locked'] = filter_var(getenv('SUITECRM_INSTALLER_LOCKED') ?: 'false', FILTER_VALIDATE_BOOLEAN);

// Timezone (provided via docker-compose.yml)
date_default_timezone_set(getenv('TZ'));

PHPEOF
    
    chown www-data:www-data "$config_file"
    chmod 640 "$config_file"
}

# ---------------------------------------------------------------------------
# Set permissions on mounted volumes (Azure Files)
# ---------------------------------------------------------------------------
set_volume_permissions() {
    echo "Setting permissions on persistent directories..."
    
    # These directories may be mounted from Azure Files
    local dirs=(
        "/var/www/html/public/legacy/upload"
        "/var/www/html/public/legacy/custom"
        "/var/www/html/public/legacy/cache"
    )
    
    for dir in "${dirs[@]}"; do
        if [ -d "$dir" ]; then
            chown -R www-data:www-data "$dir" 2>/dev/null || true
            chmod -R 775 "$dir" 2>/dev/null || true
        else
            mkdir -p "$dir"
            chown www-data:www-data "$dir"
            chmod 775 "$dir"
        fi
    done
}

# ---------------------------------------------------------------------------
# Main startup sequence
# ---------------------------------------------------------------------------
main() {
    # Set permissions first
    set_volume_permissions
    
    # Generate configuration files from environment
    generate_legacy_env
    generate_config_override
    
    # Wait for database if not skipping
    if [ "${SKIP_DB_WAIT:-false}" != "true" ]; then
        wait_for_db
    fi
    
    echo "=== Starting Apache ==="
    
    # Execute the CMD (apache2-foreground)
    exec "$@"
}

main "$@"
