#!/bin/bash
set -e

echo "=== SuiteCRM Container Startup ==="

# ---------------------------------------------------------------------------
# Wait for database to be available
# ---------------------------------------------------------------------------
wait_for_db() {
    echo "Waiting for database at ${DATABASE_HOST}:${DATABASE_PORT}..."
    
    max_attempts=30
    attempt=1
    
    while [ $attempt -le $max_attempts ]; do
        if php -r "
            \$conn = @new mysqli(
                '${DATABASE_HOST}',
                '${DATABASE_USER}',
                '${DATABASE_PASSWORD}',
                '${DATABASE_NAME}',
                ${DATABASE_PORT}
            );
            if (\$conn->connect_error) {
                exit(1);
            }
            exit(0);
        " 2>/dev/null; then
            echo "Database connection successful!"
            return 0
        fi
        
        echo "Attempt $attempt/$max_attempts - Database not ready, waiting..."
        sleep 5
        attempt=$((attempt + 1))
    done
    
    echo "WARNING: Could not connect to database after $max_attempts attempts"
    echo "Container will start anyway - SuiteCRM installer may be needed"
    return 0
}

# ---------------------------------------------------------------------------
# Generate SuiteCRM legacy .env file from environment variables
# ---------------------------------------------------------------------------
generate_legacy_env() {
    local env_file="/var/www/html/public/legacy/.env"
    
    echo "Generating SuiteCRM legacy .env from environment variables..."
    
    cat > "$env_file" << EOF
# Auto-generated by docker-entrypoint.sh
# Do not edit manually - changes will be lost on container restart

DATABASE_URL="mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}"
EOF
    
    chown www-data:www-data "$env_file"
    chmod 640 "$env_file"
}

# ---------------------------------------------------------------------------
# Generate or update config_override.php for cloud-native settings
# ---------------------------------------------------------------------------
generate_config_override() {
    local config_file="/var/www/html/public/legacy/config_override.php"
    
    echo "Generating config_override.php for cloud-native deployment..."
    
    cat > "$config_file" << 'PHPEOF'
<?php
// Auto-generated by docker-entrypoint.sh
// Cloud-native configuration for Azure Container Apps

// Database configuration from environment
$sugar_config['dbconfig']['db_host_name'] = getenv('DATABASE_HOST') ?: 'localhost';
$sugar_config['dbconfig']['db_port'] = getenv('DATABASE_PORT') ?: '3306';
$sugar_config['dbconfig']['db_user_name'] = getenv('DATABASE_USER') ?: 'suitecrm';
$sugar_config['dbconfig']['db_password'] = getenv('DATABASE_PASSWORD') ?: '';
$sugar_config['dbconfig']['db_name'] = getenv('DATABASE_NAME') ?: 'suitecrm';
$sugar_config['dbconfig']['db_type'] = 'mysql';
$sugar_config['dbconfig']['db_manager'] = 'MysqliManager';

// Azure MySQL requires SSL
$sugar_config['dbconfig']['db_ssl_enabled'] = filter_var(getenv('DATABASE_SSL_ENABLED') ?: 'true', FILTER_VALIDATE_BOOLEAN);
$sugar_config['dbconfig']['db_ssl_ca'] = getenv('DATABASE_SSL_CA') ?: '/etc/ssl/certs/ca-certificates.crt';
$sugar_config['dbconfig']['db_ssl_verify'] = filter_var(getenv('DATABASE_SSL_VERIFY') ?: 'true', FILTER_VALIDATE_BOOLEAN);

// Site URL from environment
$sugar_config['site_url'] = getenv('SUITECRM_SITE_URL') ?: 'http://localhost';

// Session handling - use database for stateless containers
$sugar_config['session_dir'] = '';
$sugar_config['session_gc'] = array(
    'enable' => true,
    'gc_probability' => 1,
    'gc_divisor' => 100,
);

// Cache configuration
$sugar_config['cache_dir'] = 'cache/';
$sugar_config['external_cache_disabled'] = false;

// Log configuration - output to stdout for container logging
$sugar_config['log_dir'] = '/dev';
$sugar_config['log_file'] = 'stdout';
$sugar_config['logger']['level'] = getenv('SUITECRM_LOG_LEVEL') ?: 'warning';

// Upload settings
$sugar_config['upload_dir'] = 'upload/';
$sugar_config['upload_maxsize'] = 104857600; // 100MB

// Disable installer after first run
$sugar_config['installer_locked'] = filter_var(getenv('SUITECRM_INSTALLER_LOCKED') ?: 'false', FILTER_VALIDATE_BOOLEAN);

// Timezone
date_default_timezone_set(getenv('TZ') ?: 'UTC');

PHPEOF
    
    chown www-data:www-data "$config_file"
    chmod 640 "$config_file"
}

# ---------------------------------------------------------------------------
# Set permissions on mounted volumes (Azure Files)
# ---------------------------------------------------------------------------
set_volume_permissions() {
    echo "Setting permissions on persistent directories..."
    
    # These directories may be mounted from Azure Files
    local dirs=(
        "/var/www/html/public/legacy/upload"
        "/var/www/html/public/legacy/custom"
        "/var/www/html/public/legacy/cache"
    )
    
    for dir in "${dirs[@]}"; do
        if [ -d "$dir" ]; then
            chown -R www-data:www-data "$dir" 2>/dev/null || true
            chmod -R 775 "$dir" 2>/dev/null || true
        else
            mkdir -p "$dir"
            chown www-data:www-data "$dir"
            chmod 775 "$dir"
        fi
    done
}

# ---------------------------------------------------------------------------
# Main startup sequence
# ---------------------------------------------------------------------------
main() {
    # Set permissions first
    set_volume_permissions
    
    # Generate configuration files from environment
    generate_legacy_env
    generate_config_override
    
    # Wait for database if not skipping
    if [ "${SKIP_DB_WAIT:-false}" != "true" ]; then
        wait_for_db
    fi
    
    echo "=== Starting Apache ==="
    
    # Execute the CMD (apache2-foreground)
    exec "$@"
}

main "$@"
